# routes/generate_outfit_demo.py
from fastapi import APIRouter, Form, HTTPException
from fastapi.responses import JSONResponse
from google import genai
from google.genai import types
from firebase_admin import firestore
import base64, os, traceback
from dotenv import load_dotenv

load_dotenv()
router = APIRouter()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
db = firestore.client()

@router.post("/generate_outfit_demo")
async def generate_outfit_demo(user_id: str = Form(...)):
    """
    Generate 3 demo outfits using the stored base model (face + body measurements).
    Returns: JSON with 3 base64 images.
    """
    try:
        # ------------------ FETCH USER BASE MODEL ------------------
        doc = db.collection("user_models").document(user_id).get()
        if not doc.exists:
            raise HTTPException(status_code=404, detail="User base model not found.")

        user_data = doc.to_dict()
        face_url = user_data.get("face_url")  # matches register_base_model
        measurements = user_data.get("measurements", {})
        body_type = user_data.get("body_type", "normal")

        # ------------------ BUILD PROMPT ------------------
        prompt = f"""
You already have the base model of this user, including face and body proportions.
Generate 3 full-body images with different outfits (casual, elegant, sporty).
Maintain exactly the same face and body structure without any distortion.
Body type: {body_type}
Measurements: {measurements}
Use the face image from: {face_url}
Return the 3 generated images as base64 strings.
"""

        # ------------------ CALL GEMINI ------------------
        result = client.models.generate_content(
            model="gemini-1.5-pro",
            contents=[types.Part.from_text(prompt)],
        )

        # ------------------ PARSE RESPONSE ------------------
        demo_images = []
        if hasattr(result, "candidates") and result.candidates:
            for cand in result.candidates:
                if getattr(cand, "content", None) and getattr(cand.content, "parts", None):
                    for part in cand.content.parts:
                        if getattr(part, "inline_data", None) and getattr(part.inline_data, "data", None):
                            # Convert bytes to base64 string
                            b64_str = f"data:{part.inline_data.mime_type};base64,{base64.b64encode(part.inline_data.data).decode()}"
                            demo_images.append(b64_str)

        if not demo_images:
            raise HTTPException(status_code=500, detail="No images generated by AI.")

        # Take only first 3 images
        demo_images = demo_images[:3]

        return JSONResponse({
            "status": "ok",
            "demo_outfits": demo_images
        })

    except Exception as e:
        print("❌ Error in /generate_outfit_demo:", traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))
