from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from google import genai
from google.genai import types
import base64, traceback, os

router = APIRouter()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=GEMINI_API_KEY)

@router.post("/generate_outfit_demo")
async def generate_outfit_demo(payload: dict):
    """
    Generate 3 demo outfits using provided user data (face + body measurements).
    Expects JSON payload:
    {
        "measurements": {...},
        "face_base64": "data:image/png;base64,...",
        "base_photo_url": "https://...",
        "gender": "male" | "female"
    }
    Returns: JSON with 3 base64 images.
    """
    try:
        measurements = payload.get("measurements")
        face_base64 = payload.get("face_base64")
        gender = payload.get("gender", "unknown")
        base_photo_url = payload.get("base_photo_url")

        if not measurements or not face_base64:
            raise HTTPException(status_code=400, detail="Missing measurements or face image.")

        prompt = f"""
You already have the user's body measurements and face image.
Generate 3 full-body images with different outfits (casual, elegant, sporty).
Maintain exactly the same face and body structure without distortion.
Gender: {gender}
Measurements: {measurements}
Use the face image provided in base64.
Return the 3 generated images as base64 strings.
"""

        # Llamada a Gemini
        result = client.models.generate_content(
            model="gemini-1.5-pro",
            contents=[types.Part.from_text(text=prompt)],  # ✅ Keyword correcto
        )

        demo_images = []
        if hasattr(result, "candidates") and result.candidates:
            for cand in result.candidates:
                if getattr(cand, "content", None) and getattr(cand.content, "parts", None):
                    for part in cand.content.parts:
                        if getattr(part, "inline_data", None) and getattr(part.inline_data, "data", None):
                            b64_str = f"data:{part.inline_data.mime_type};base64,{base64.b64encode(part.inline_data.data).decode()}"
                            demo_images.append(b64_str)

        if not demo_images:
            raise HTTPException(status_code=500, detail="No images generated by AI.")

        return JSONResponse({
            "status": "ok",
            "demo_outfits": demo_images[:3]
        })

    except Exception as e:
        print("❌ Error in /generate_outfit_demo:", traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))
