# routes/generate_outfit_demo.py
from fastapi import APIRouter, Form, HTTPException
from fastapi.responses import JSONResponse
from google import genai
from google.genai import types
from firebase_admin import firestore
import os, traceback
from dotenv import load_dotenv

load_dotenv()
router = APIRouter()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

db = firestore.client()

@router.post("/generate_outfit_demo")
async def generate_outfit_demo(user_id: str = Form(...)):
    try:
        # Buscar datos base del usuario
        doc = db.collection("user_models").document(user_id).get()
        if not doc.exists:
            raise HTTPException(status_code=404, detail="User base model not found.")

        user_data = doc.to_dict()
        face_url = user_data.get("face_ref")
        measurements = user_data.get("measurements", {})
        contexture = user_data.get("contexture", "average")

        # --- Prompt de generación demo ---
        prompt = f"""
You already have the base model of this user, including face and body proportions.
Now generate 3 full-body images with different outfits (casual, elegant, and sporty).
Maintain exactly the same face and body structure.
User body type: {contexture}
Measurements: {measurements}
Use the face image from: {face_url}
Return the 3 generated images.
"""

        result = client.models.generate_content(
            model="gemini-1.5-pro",
            contents=[types.Part.from_text(prompt)],
        )

        # Obtener URLs o base64s generadas (según lo que devuelva tu IA)
        # Gemini típicamente devuelve las imágenes como base64
        if hasattr(result, "candidates") and result.candidates:
            images = []
            for c in result.candidates:
                if c.content and c.content.parts:
                    for p in c.content.parts:
                        if hasattr(p, "inline_data") and p.inline_data:
                            images.append(p.inline_data.data)
            if not images:
                raise Exception("No images generated by AI.")
        else:
            raise Exception("Gemini returned no candidates.")

        return JSONResponse({"status": "ok", "demo_outfits": images})

    except Exception as e:
        print("❌ Error:", traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))
