name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render backend
        run: |
          curl -L -X GET https://wink-backend-1jao.onrender.com/api/ping
